-- Tables

-- 1) PAIS
CREATE TABLE PAISES (
    ID_PAIS NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(28) NOT NULL,
    NACIONALIDAD VARCHAR2(36) NOT NULL,
    CONTINENTE VARCHAR2(7) NOT NULL CONSTRAINT CHK_PAIS_CONTINENTE CHECK (CONTINENTE IN ('AMERICA','AFRICA','ASIA','EUROPA','OCEANIA')),
    UNION_EUROPEA NUMBER(1) NOT NULL CONSTRAINT CHK_PAIS_UNION_EUROPEA CHECK (UNION_EUROPEA IN (0,1))
);

-- 2) INSIDE_TOURS
CREATE TABLE INSIDE_TOURS (
    F_INICIO DATE PRIMARY KEY,
    PRECIO_PERSONA NUMBER(7,2) NOT NULL CONSTRAINT CHK_INSIDE_TOUR_PRECIO CHECK (PRECIO_PERSONA > 0),
    TOTAL_CUPOS NUMBER(4) NOT NULL CONSTRAINT CHK_INSIDE_TOUR_CUPOS CHECK (TOTAL_CUPOS > 0)
);

-- 3) CLIENTES_LEGO
CREATE TABLE CLIENTES_LEGO (
    ID_CLIENTE NUMBER(4) PRIMARY KEY,
    P_NOMBRE VARCHAR2(28) NOT NULL,
    P_APELLIDO VARCHAR2(28) NOT NULL,
    S_APELLIDO VARCHAR2(28) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    NUM_DOC VARCHAR2(50) NOT NULL CONSTRAINT UNQ_CLIENTE_DOC_NAC UNIQUE,
    TELEFONO VARCHAR2(20) NOT NULL CONSTRAINT CHK_CLIENTE_TELEFONO CHECK (REGEXP_LIKE(TELEFONO, '^\+?\d{1,3}( ?\d+)+$')),
    NACIMIENTO NUMBER(4) NOT NULL CONSTRAINT FK_CLIENTE_NACIMIENTO_PAIS REFERENCES PAISES (ID_PAIS),
    RESIDENCIA NUMBER(4) NOT NULL CONSTRAINT FK_CLIENTE_RESIDENCIA_PAIS REFERENCES PAISES (ID_PAIS),
    S_NOMBRE VARCHAR2(28),
    NUM_PASS VARCHAR2(50) CONSTRAINT UNQ_CLIENTE_NUM_PASS UNIQUE,
    F_VEN_PASS DATE,
    EMAIL VARCHAR2(254) CONSTRAINT CHK_CLIENTE_EMAIL CHECK (EMAIL IS NULL OR REGEXP_LIKE(EMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,63}$'))
);

-- 4) FANS_MENOR_LEGO
CREATE TABLE FANS_MENOR_LEGO (
    ID_FAN NUMBER(4) PRIMARY KEY,
    P_NOMBRE VARCHAR2(28) NOT NULL,
    P_APELLIDO VARCHAR2(28) NOT NULL,
    S_APELLIDO VARCHAR2(28) NOT NULL,
    NACIMIENTO NUMBER(4) NOT NULL CONSTRAINT FK_FAN_NACIMIENTO_PAIS REFERENCES PAISES (ID_PAIS),
    FECHA_NAC DATE NOT NULL,
    NUM_DOC VARCHAR2(50) NOT NULL CONSTRAINT UNQ_FAN_DOC_NAC UNIQUE,
    S_NOMBRE VARCHAR2(28),
    ID_REPRESENTANTE NUMBER(4) CONSTRAINT FK_FAN_REPRESENTANTE REFERENCES CLIENTES_LEGO (ID_CLIENTE),
    NUM_PASS VARCHAR2(50) CONSTRAINT UNQ_FAN_NUM_PASS UNIQUE,
    F_VEN_PASS DATE
);

-- 5) INSCRIPCIONES_TOUR
CREATE TABLE INSCRIPCIONES_TOUR (
    F_INICIO DATE NOT NULL CONSTRAINT FK_INSCRIPCION_F_INICIO REFERENCES INSIDE_TOURS (F_INICIO),
    NUM_INSCRIPCION NUMBER(4),
    TOTAL NUMBER(9,2) NOT NULL CONSTRAINT CHK_INSCRIPCION_TOTAL CHECK (TOTAL >= 0),
    F_INSCRIPCION DATE NOT NULL,
    STATUS_CONF VARCHAR2(10) NOT NULL CONSTRAINT CHK_INSCRIPCION_STATUS CHECK (STATUS_CONF IN ('PENDIENTE', 'PAGO')),
    CONSTRAINT PK_INSCRIPCION PRIMARY KEY (NUM_INSCRIPCION, F_INICIO)
);

-- 6) INSCRITOS
CREATE TABLE INSCRITOS (
    F_INICIO DATE NOT NULL,
    NUM_INSCRIPCION NUMBER(4) NOT NULL,
    ID_INSCRITOS NUMBER(4),
    PARTICIPANTE_MENOR NUMBER(4) CONSTRAINT FK_INSCRITOS_PART_MENOR REFERENCES FANS_MENOR_LEGO (ID_FAN),
    PARTICIPANTE_MAYOR NUMBER(4) CONSTRAINT FK_INSCRITOS_PART_MAYOR REFERENCES CLIENTES_LEGO (ID_CLIENTE),
    CONSTRAINT FK_INSCRITOS_INSCRIPCION_FULL FOREIGN KEY (NUM_INSCRIPCION, F_INICIO) REFERENCES INSCRIPCIONES_TOUR (NUM_INSCRIPCION, F_INICIO),
    CONSTRAINT PK_INSCRITOS PRIMARY KEY (F_INICIO, NUM_INSCRIPCION, ID_INSCRITOS),
    CONSTRAINT CHK_INSCRITOS_PARTICIPANT_XOR CHECK (
        (PARTICIPANTE_MENOR IS NOT NULL AND PARTICIPANTE_MAYOR IS NULL) OR
        (PARTICIPANTE_MENOR IS NULL AND PARTICIPANTE_MAYOR IS NOT NULL)
    )
);

-- 7) ENTRADAS
CREATE TABLE ENTRADAS (
    F_INICIO DATE NOT NULL,
    NUM_INSCRIPCION NUMBER(4) NOT NULL,
    NUM_ENTRADA NUMBER(4),
    TIPO VARCHAR2(7) NOT NULL CONSTRAINT CHK_ENTRADA_TIPO CHECK (TIPO IN ('MENOR','REGULAR')),
    CONSTRAINT FK_ENTRADA_INSCRIPCION_FULL FOREIGN KEY (NUM_INSCRIPCION, F_INICIO) REFERENCES INSCRIPCIONES_TOUR (NUM_INSCRIPCION, F_INICIO),
    CONSTRAINT PK_ENTRADA PRIMARY KEY (F_INICIO, NUM_INSCRIPCION, NUM_ENTRADA)
);

-- 8) ESTADOS
CREATE TABLE ESTADOS (
    ID_PAIS NUMBER(4) NOT NULL,
    ID_ESTADO NUMBER(4) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_ESTADOS FOREIGN KEY (ID_PAIS) REFERENCES PAISES (ID_PAIS),
    CONSTRAINT PK1_ESTADOS PRIMARY KEY (ID_PAIS, ID_ESTADO)
);

-- 9) CIUDADES
CREATE TABLE CIUDADES (
    ID_PAIS NUMBER(4) NOT NULL,
    ID_ESTADO NUMBER(4) NOT NULL,
    ID_CIUDAD NUMBER(4) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONSTRAINT FK1_CIUDADES FOREIGN KEY (ID_PAIS, ID_ESTADO) REFERENCES ESTADOS (ID_PAIS, ID_ESTADO),
    CONSTRAINT PK1_CIUDADES PRIMARY KEY (ID_PAIS, ID_ESTADO, ID_CIUDAD)
);

-- 10) TIENDAS
CREATE TABLE TIENDAS (
    ID_TIENDA NUMBER(4) PRIMARY KEY,
    ID_PAIS NUMBER(4) NOT NULL,
    ID_ESTADO NUMBER(4) NOT NULL,
    ID_CIUDAD NUMBER(4) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DIRECCION VARCHAR2(200) NOT NULL,
    TELEFONO VARCHAR2(17) NOT NULL,
    CONSTRAINT FK1_TIENDAS FOREIGN KEY (ID_PAIS, ID_ESTADO, ID_CIUDAD) REFERENCES CIUDADES (ID_PAIS, ID_ESTADO, ID_CIUDAD),
    CONSTRAINT CHK_TIENDA_TELEFONO CHECK (TELEFONO IS NULL OR REGEXP_LIKE(TELEFONO, '^\+?\d{1,3}( ?\d+)+$'))
);

-- 11) HORARIOS
CREATE TABLE HORARIOS (
    ID_TIENDA NUMBER(4) NOT NULL,
    DIA NUMBER(1) NOT NULL,
    HORA_INICIO DATE NOT NULL, 
    HORA_FIN DATE NOT NULL,
    CONSTRAINT FK_HORARIOS FOREIGN KEY (ID_TIENDA) REFERENCES TIENDAS (ID_TIENDA),
    CONSTRAINT PK1_HORARIOS PRIMARY KEY (ID_TIENDA,DIA),
    CONSTRAINT CHK_DIA_VALIDO CHECK (DIA BETWEEN 1 AND 7),
    CONSTRAINT CHK_HORA_INICIO_FORMATO CHECK (REGEXP_LIKE(TO_CHAR(HORA_INICIO, 'HH24:MI:SS'), '^[0-2][0-9]:[0-5][0-9]:[0-5][0-9]$')),
    CONSTRAINT CHK_HORA_FIN_FORMATO CHECK (REGEXP_LIKE(TO_CHAR(HORA_FIN, 'HH24:MI:SS'), '^[0-2][0-9]:[0-5][0-9]:[0-5][0-9]$'))
);

CREATE TABLE TEMAS (
    ID_TEMA           NUMBER(4)      PRIMARY KEY,
    NOMBRE_TEMA       VARCHAR2(40)   NOT NULL,
    DESCRIPCION_TEMA  VARCHAR2(200)  NOT NULL,
    TIPO_TEMA         VARCHAR2(10)   NOT NULL,
    LICENCIA_EXTERNA  NUMBER(1),
    CONSTRAINT CHK_TEMA_TIPO CHECK (TIPO_TEMA IN ('TEMA','SERIE')),
    CONSTRAINT CHK_TEMA_LIC_EXTERNA CHECK (LICENCIA_EXTERNA IN (0,1))
);

CREATE TABLE JUGUETES (
    ID_JUGUETE           NUMBER(5)    PRIMARY KEY,
    ID_TEMA              NUMBER(4)    NOT NULL,
    NOMBRE_JUGUETE       VARCHAR2(100) NOT NULL,
    RANGO_EDAD           VARCHAR2(20) NOT NULL,
    NUMERO_PIEZAS        NUMBER(5)    NOT NULL CONSTRAINT CHK_JUGUETE_NUM_PIEZAS CHECK (NUMERO_PIEZAS > 0),
    ES_SET               NUMBER(1)    NOT NULL CONSTRAINT CHK_JUGUETE_ES_SET CHECK (ES_SET IN (0,1)),
    ARCHIVO_INSTRUCCIONES VARCHAR2(255),
    RANGO_PRECIO         CHAR(1)      NOT NULL CONSTRAINT CHK_JUGUETE_RANGO_PRECIO CHECK (RANGO_PRECIO IN ('A','B','C','D')),
    DESCRIPCION          VARCHAR2(400) NOT NULL,
    CONSTRAINT FK_JUGUETE_TEMA FOREIGN KEY (ID_TEMA) REFERENCES TEMAS (ID_TEMA)
);

-- 12) CATALOGO_PAIS
CREATE TABLE CATALOGO_PAIS (
    ID_PAIS NUMBER(4) NOT NULL,
    ID_JUGUETE NUMBER(5) NOT NULL,
    LIMITE_COMPRA NUMBER(4) NOT NULL,
    CONSTRAINT FK1_CATALOGO FOREIGN KEY (ID_PAIS) REFERENCES PAISES(ID_PAIS),
    CONSTRAINT FK2_CATALOGO FOREIGN KEY (ID_JUGUETE) REFERENCES JUGUETES(ID_JUGUETE),
    CONSTRAINT PK1_CATALOGO PRIMARY KEY (ID_PAIS, ID_JUGUETE)
);

CREATE TABLE LOTES_INVENTARIO (
    NUMERO_LOTE  NUMBER(6)   NOT NULL,
    ID_TIENDA    NUMBER(4)   NOT NULL,
    ID_JUGUETE   NUMBER(5)   NOT NULL,
    CANTIDAD     NUMBER(6)   NOT NULL CONSTRAINT CHK_LOTE_CANTIDAD CHECK (CANTIDAD >= 0),
    CONSTRAINT FK_LOTE_TIENDA FOREIGN KEY (ID_TIENDA) REFERENCES TIENDAS (ID_TIENDA),
    CONSTRAINT FK_LOTE_JUGUETE FOREIGN KEY (ID_JUGUETE) REFERENCES JUGUETES (ID_JUGUETE),
    CONSTRAINT PK_LOTES_INVENTARIO PRIMARY KEY (NUMERO_LOTE,ID_TIENDA,ID_JUGUETE)
);

CREATE TABLE DESCUENTOS_INVENTARIO (
    ID_DESCUENTO  NUMBER(6)  PRIMARY KEY,
    ID_PAIS       NUMBER(4)  NOT NULL,
    ID_JUGUETE    NUMBER(5)  NOT NULL,
    FECHA         DATE       NOT NULL,
    CANTIDAD      NUMBER(6)  NOT NULL CONSTRAINT CHK_DESC_INV_CANTIDAD CHECK (CANTIDAD > 0),
    CONSTRAINT FK_DESC_INV_CATALOGO FOREIGN KEY (ID_PAIS, ID_JUGUETE) REFERENCES CATALOGO_PAIS (ID_PAIS, ID_JUGUETE)
);

CREATE TABLE HISTORICO_PRECIO (
    ID_JUGUETE    NUMBER(5)   NOT NULL,
    FECHA_INICIO  DATE        NOT NULL,
    PRECIO        NUMBER(8,2) NOT NULL CONSTRAINT CHK_HPRECIO_POSITIVO CHECK (PRECIO > 0),
    FECHA_FIN     DATE,
    CONSTRAINT PK_HISTORICO_PRECIO PRIMARY KEY (ID_JUGUETE, FECHA_INICIO),
    CONSTRAINT FK_HPRECIO_JUGUETE FOREIGN KEY (ID_JUGUETE) REFERENCES JUGUETES (ID_JUGUETE),
    CONSTRAINT CHK_HPRECIO_INTERVALO CHECK (FECHA_FIN IS NULL OR FECHA_FIN > FECHA_INICIO)
);

CREATE TABLE Factura_Fisica(
    id_tienda number(4) not null,
    num_factura number(6) not null,
    id_cliente number(4) not null,
    fecha_emision timestamp not null,
    total number(9,2),
    constraint Factura_Fisic_id_tienda foreign key (id_tienda) REFERENCES TIENDAS (ID_TIENDA),
    CONSTRAINT id_factura_fisica PRIMARY KEY (id_tienda,num_factura),
    CONSTRAINT Factura_Fisic_id_cliente foreign key (id_cliente) REFERENCES CLIENTES_LEGO(ID_CLIENTE)
);

CREATE TABLE Det_Factura_Fis(
    id_tienda number(4) not null,
    num_factura number(6) not null,
    id_det_fact number(6) not null,
    NUMERO_LOTE  NUMBER(6)   NOT NULL,
    -- ID_TIENDA NUMBER(4) NOT NULL, -- duplicado en la llave foranea de arriba
    ID_JUGUETE   NUMBER(5)   NOT NULL,
    tipo_cliente varchar2(11) CONSTRAINT Det_Factura_Fis_tipo_cliente CHECK(tipo_cliente in ('NINNO', 'ADOLESCENTE', 'ADULTO')),
    constraint Det_Factura_Fis_id_Factura_Fisica FOREIGN KEY (id_tienda,num_factura) REFERENCES Factura_Fisica(id_tienda,num_factura),
    constraint id_Det_Factura_Fis PRIMARY KEY (id_tienda,num_factura,id_det_fact),
    CONSTRAINT Det_Factura_Fis_LOTES_INVENTARIO FOREIGN KEY (NUMERO_LOTE,ID_TIENDA,ID_JUGUETE) REFERENCES LOTES_INVENTARIO(NUMERO_LOTE,ID_TIENDA,ID_JUGUETE)
);

CREATE TABLE Factura_online(
    num_factura number(4) primary key,
    f_emision timestamp not null,
    id_cliente number(4) not null,
    puntos_acum_venta number(3) not null,
    gratis_lealtad NUMBER(1) not null,
    total number(9,2),
    CONSTRAINT CHK_GRATIS_LEALTAD CHECK (gratis_lealtad IN (0,1)),
    CONSTRAINT Factura_online_id_cliente foreign key (id_cliente) REFERENCES CLIENTES_LEGO(ID_CLIENTE)
);

CREATE TABLE Det_Factura_Onl(
    num_factura number(4) not null,
    id_det_fact number(6) not null,
    id_pais number(4) not null,
    ID_JUGUETE NUMBER(5) not null,
    cantidad number(2),
    CONSTRAINT Det_Factura_Onl_num_factura foreign key (num_factura) REFERENCES Factura_online(num_factura),
    CONSTRAINT id_Det_Factura_Onl primary key (num_factura,id_det_fact),
    CONSTRAINT Det_Factura_Onl_id_catalogo foreign key (id_pais,id_juguete) REFERENCES CATALOGO_PAIS (ID_PAIS,ID_JUGUETE)
);
